# =============================================================================
# Project     : Knap, a pure Mojo byte level BPE tokenizer
# File        : scripts/gen_api_reference.py
# Purpose     : Generates docs/API.md from the compiler's own docstring
#               extraction, so the public surface is reviewable in a diff.
# Stage       : Repository standard enforcement, see docs/STYLE.md
# Depends on  : The pinned Mojo compiler, for mojo doc.
# Invariants  : Only the public surface is emitted. A name beginning with an
#               underscore is internal and stays out, so the document says
#               what a consumer may rely on rather than what exists.
# -----------------------------------------------------------------------------
# Author      : Olaf Yunus Laitinen Imanov <yunus.imanov@metropolia.fi>
# ORCID       : 0009-0006-5184-0810
# Affiliation : School of Information and Communication Technology,
#               Metropolia University of Applied Sciences
# -----------------------------------------------------------------------------
# SPDX-License-Identifier: EUPL-1.2
# Copyright 2026 Olaf Yunus Laitinen Imanov
# =============================================================================
"""Generate the API reference for Knap.

`mojo doc` extracts docstrings into JSON and does not generate HTML. Its own
help says the format is subject to change. That rules out building a
documentation site against it: the cost would be a renderer, and the
foundation is declared unstable by the tool that produces it. The same
reasoning keeps a Python wheel unpublished.

So this renders Markdown into the repository instead, and that turns out to
be the better artefact for this project rather than a consolation prize.

  * It renders on the forge with no site to deploy or keep alive.
  * It is committed, so `scripts/check_generated.py` fails the build when it
    drifts from the code.
  * **A change to the public surface appears in a pull request diff.** For a
    version that claims a settled interface, that is worth more than a
    browsable page. Adding a method, or quietly widening one, becomes
    something a reviewer sees rather than something they would have to go
    looking for.

Underscore prefixed names are omitted. The document is a statement about what
a consumer may rely on, and internals in it would be an invitation to rely on
those too.

    python scripts/gen_api_reference.py
    python scripts/gen_api_reference.py --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE = REPO_ROOT / "src" / "knap"
OUTPUT = REPO_ROOT / "docs" / "API.md"

HEADER = """<!--
  SPDX-License-Identifier: EUPL-1.2
  Copyright 2026 Olaf Yunus Laitinen Imanov
  Part of the Knap project. See LICENSE for terms.
-->

# Knap API Reference

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)"
            srcset="assets/knap_logo_transparent_white.svg">
    <img src="assets/knap_logo_transparent_black.svg"
         alt="Knap" width="240">
  </picture>
</p>

| Field | Value |
| --- | --- |
| Document | `docs/API.md` |
| Project | Knap, a pure Mojo byte level BPE tokenizer |
| Version | 1.0.0 |
| Status | Draft |
| Applies to | Knap 1.0.0, Mojo 1.0.0 |
| Author | Olaf Yunus Laitinen Imanov |
| ORCID | [0009-0006-5184-0810](https://orcid.org/0009-0006-5184-0810) |
| Affiliation | School of Information and Communication Technology, Metropolia University of Applied Sciences |
| Created | 2026-09-09 |
| Updated | 2026-09-10 |
| Licence | EUPL-1.2 |
| Website | <https://knap.lovable.app> |

---

## About this document

**Generated by `scripts/gen_api_reference.py` from `mojo doc`. Do not edit it
by hand.** `scripts/check_generated.py` fails the build if it has drifted
from the code, so an edit here is reverted by the next generator run.

Only the public surface appears. Names beginning with an underscore are
internal and are omitted deliberately: this document says what a consumer may
rely on, and listing internals would invite reliance on them.

Its real purpose is the diff. Knap 1.0.0 claims a settled interface, and a
change to that interface should be visible in a pull request rather than
something a reviewer has to go looking for. Adding a method, or widening one,
changes this file.

---

## Contents
"""

FOOTER = """
---

## Document control

| Field | Value |
| --- | --- |
| Previous | [docs/ARCHITECTURE.md](ARCHITECTURE.md) |
| Next | [docs/CORRECTNESS.md](CORRECTNESS.md) |
| Index | [README.md](../README.md) |
| Revision | 1.0.0 |
| Last reviewed | 2026-09-10 |

Knap is licensed under the European Union Public Licence 1.2.
Copyright 2026 Olaf Yunus Laitinen Imanov, Metropolia University of Applied
Sciences. See [LICENSE](../LICENSE) for the full terms.

<!-- End of document: docs/API.md -->
"""


def find_mojo() -> Path:
    """Locate the pinned Mojo compiler.

    Returns:
        Path to the compiler.

    Raises:
        SystemExit: when it cannot be found.
    """
    candidate = REPO_ROOT / ".venv" / "bin" / "mojo"
    if candidate.exists():
        return candidate
    raise SystemExit(
        "gen_api_reference: no Mojo compiler at .venv/bin/mojo. Run "
        "'uv sync --group dev' first."
    )


def extract() -> dict:
    """Run the compiler's docstring extraction over the package.

    Returns:
        The parsed JSON.

    Raises:
        SystemExit: if extraction fails.
    """
    mojo = find_mojo()
    with tempfile.TemporaryDirectory() as scratch:
        destination = Path(scratch) / "api.json"
        done = subprocess.run(
            [str(mojo), "doc", "-o", str(destination), "-I", "src", "src/knap"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if done.returncode != 0:
            print(done.stdout)
            print(done.stderr, file=sys.stderr)
            raise SystemExit("gen_api_reference: mojo doc failed")
        return json.loads(destination.read_text(encoding="utf-8"))


def is_public(name: str) -> bool:
    """Report whether a name is part of the public surface.

    Args:
        name: The declared name.

    Returns:
        True when it does not begin with an underscore.
    """
    return bool(name) and not name.startswith("_")


def summary_of(node: dict) -> str:
    """Take the first line of a declaration's docstring.

    Args:
        node: A declaration from the extraction.

    Returns:
        One line, or an empty string when there is no docstring.

    A summary rather than the whole docstring, because the whole thing is in
    the source where somebody reading the implementation will find it. This
    document exists to show the shape of the surface.
    """
    source = node
    overloads = node.get("overloads")
    if overloads:
        source = overloads[0]
    text = (source.get("summary") or source.get("description") or "").strip()
    if not text:
        return ""
    # One line, and pipes escaped: these land inside Markdown table
    # cells, where an unescaped pipe silently splits the row.
    first = " ".join(text.split("\n")[0].split())
    return first.replace("|", "\\|")


def signature_of(node: dict) -> str:
    """Render a function signature.

    Args:
        node: A function declaration, possibly with several overloads.

    Returns:
        The signature as it should appear in a code span.
    """
    overloads = node.get("overloads") or [node]
    first = overloads[0]

    # The compiler renders the signature itself, including the
    # parameter list and the raises marker. Rebuilding it by hand would
    # be a second opinion about the language's own syntax, which is not
    # a useful thing for this document to hold.
    rendered = (first.get("signature") or "").strip()
    if not rendered:
        arguments = []
        for argument in first.get("args") or []:
            name = argument.get("name", "")
            kind = argument.get("type", "")
            arguments.append(f"{name}: {kind}" if kind else name)
        rendered = (
            f"{node.get('name', '')}(" + ", ".join(arguments) + ")"
        )

    return " ".join(rendered.split()).replace("|", "\\|")


def render_module(module: dict, lines: list[str]) -> bool:
    """Render one module, if it has anything public in it.

    Args:
        module: A module declaration.
        lines: Output lines, appended to.

    Returns:
        True when something was written.
    """
    structs = [s for s in module.get("structs") or [] if is_public(s.get("name", ""))]
    functions = [
        f for f in module.get("functions") or [] if is_public(f.get("name", ""))
    ]
    aliases = [a for a in module.get("aliases") or [] if is_public(a.get("name", ""))]

    if not structs and not functions and not aliases:
        return False

    lines.append("")
    lines.append(f"### `{module.get('name', '')}`")
    text = summary_of(module)
    if text:
        lines.append("")
        lines.append(text)

    if aliases:
        lines.append("")
        lines.append("| Constant | Description |")
        lines.append("| --- | --- |")
        for alias in aliases:
            lines.append(
                f"| `{alias.get('name', '')}` | {summary_of(alias) or 'No summary.'} |"
            )

    for struct in structs:
        lines.append("")
        lines.append(f"#### `{struct.get('name', '')}`")
        text = summary_of(struct)
        if text:
            lines.append("")
            lines.append(text)
        methods = [
            m
            for m in struct.get("functions") or []
            if is_public(m.get("name", ""))
        ]
        fields = [
            f for f in struct.get("fields") or [] if is_public(f.get("name", ""))
        ]
        if fields:
            lines.append("")
            lines.append("| Field | Type | Description |")
            lines.append("| --- | --- | --- |")
            for field in fields:
                lines.append(
                    f"| `{field.get('name', '')}` | `{field.get('type', '')}` |"
                    f" {summary_of(field) or 'No summary.'} |"
                )
        if methods:
            lines.append("")
            lines.append("| Method | Description |")
            lines.append("| --- | --- |")
            for method in methods:
                lines.append(
                    f"| `{signature_of(method)}` |"
                    f" {summary_of(method) or 'No summary.'} |"
                )

    if functions:
        lines.append("")
        lines.append("| Function | Description |")
        lines.append("| --- | --- |")
        for function in functions:
            lines.append(
                f"| `{signature_of(function)}` |"
                f" {summary_of(function) or 'No summary.'} |"
            )
    return True


def walk(node: dict, lines: list[str], contents: list[str]) -> None:
    """Render a package and everything public under it.

    Args:
        node: A package declaration.
        lines: Output lines, appended to.
        contents: Contents entries, appended to.
    """
    for module in node.get("modules") or []:
        name = module.get("name", "")
        if not is_public(name) and name != "__init__":
            continue
        if name == "__init__":
            continue
        if render_module(module, lines):
            contents.append(name)
    for package in node.get("packages") or []:
        walk(package, lines, contents)


def build() -> str:
    """Build the whole document.

    Returns:
        Its text.
    """
    root = extract().get("decl", {})
    lines: list[str] = []
    contents: list[str] = []
    walk(root, lines, contents)

    # The Contents lists both top level sections, then the modules nested
    # under the one they belong to. Listing only the modules left the two
    # sections unlisted, which the Markdown gate now refuses: a Contents list
    # that omits a section is one a reader trusts and stops scrolling past.
    head = [HEADER]
    head.append("1. [About this document](#about-this-document)")
    head.append("2. [Modules](#modules)")
    for name in contents:
        # The forge keeps underscores in a heading slug and strips the
        # backticks. Replacing them produced anchors resolving to
        # nothing, which the Markdown gate caught.
        head.append(f"    - [`{name}`](#{name})")
    head.append("")
    head.append("---")
    head.append("")
    head.append("## Modules")

    return "\n".join(head + lines) + "\n" + FOOTER


def main() -> int:
    """Write or check the API reference."""
    parser = argparse.ArgumentParser(
        description="Generate docs/API.md from mojo doc."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed file is not what this would write.",
    )
    arguments = parser.parse_args()

    text = build()

    if arguments.check:
        if not OUTPUT.is_file():
            print("gen_api_reference: docs/API.md is missing", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != text:
            print(
                "gen_api_reference: docs/API.md has drifted from the code. "
                "Run 'python scripts/gen_api_reference.py'.",
                file=sys.stderr,
            )
            return 1
        print("gen_api_reference: committed API.md is current.")
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"gen_api_reference: wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

# =============================================================================
# End of file: scripts/gen_api_reference.py
# =============================================================================
